name = "Judo"
uuid = "4ff32cee-1a95-4b6f-aa6c-81a2608e045c"
authors = ["Fang Liu <fangliu@tju.edu.cn> and contributors"]
version = "1.0.0-DEV"

[deps]
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
